spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://10.1.1.11:3306/flysky
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

mytest:
  abc: 1234
#logging:
#  level:
#    root: info
#    org.springframework: off

#查看当前SpringBoot AutoConfig的一些配置项
#debug: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
