spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/flysky
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
#    exclude: org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
mybatis:
  mapper-locations: classpath:mapper/*.xml
debug: true