#============================#
#==== Redis settings ====#
#============================#
#redis 服务器 IP
spring:
  redis:
    host: 192.168.0.110
  datasource:
    url: 1234
    data-username: root
    data-password: 123456
    driver-class-name: